import { Icon, environment } from "@vicinae/api";

const pdfIcon = `${environment.assetsPath}/file_icons/pdf.svg`;
const powerpointIcon = `${environment.assetsPath}/file_icons/powerpoint.svg`;
const sheetsIcon = `${environment.assetsPath}/file_icons/sheets.svg`;
const textDocIcon = `${environment.assetsPath}/file_icons/text_doc.svg`;
const jupyterIcon = `${environment.assetsPath}/file_icons/jupyter.svg`;
const imageIcon = `${environment.assetsPath}/file_icons/image.svg`;
export const genericFileIcon = `${environment.assetsPath}/file_icons/generic_file.svg`;

/** Maps normalized file extensions to either Vicinae icons or bundled asset icons. */
export const EXTENSION_ICON_MAP: Record<string, Icon | string> = {
  json: Icon.Json,
  jsonc: Icon.Json,
  json5: Icon.Json,
  yaml: Icon.Yaml,
  yml: Icon.Yaml,
  toml: Icon.Code,
  ini: Icon.Code,
  conf: Icon.Code,
  config: Icon.Code,
  md: Icon.Markdown,
  markdown: Icon.Markdown,
  mdx: Icon.Markdown,
  txt: Icon.BlankDocument,
  rst: Icon.BlankDocument,
  pdf: pdfIcon,
  doc: textDocIcon,
  docx: textDocIcon,
  odt: textDocIcon,
  rtf: textDocIcon,
  xls: sheetsIcon,
  xlsx: sheetsIcon,
  ods: sheetsIcon,
  csv: sheetsIcon,
  tsv: sheetsIcon,
  ppt: powerpointIcon,
  pptx: powerpointIcon,
  odp: powerpointIcon,
  ipynb: jupyterIcon,
  nblink: jupyterIcon,
  c: Icon.C,
  h: Icon.C,
  cpp: Icon.Cplusplus,
  cxx: Icon.Cplusplus,
  cc: Icon.Cplusplus,
  hpp: Icon.Cplusplus,
  hxx: Icon.Cplusplus,
  hh: Icon.Cplusplus,
  cs: Icon.Csharp,
  js: Icon.Javascript,
  cjs: Icon.Javascript,
  mjs: Icon.Javascript,
  jsx: Icon.Javascript,
  ts: Icon.Typescript,
  tsx: Icon.Typescript,
  "d.ts": Icon.Typescript,
  py: Icon.Python,
  java: Icon.Java,
  kt: Icon.Kotlin,
  kts: Icon.Kotlin,
  swift: Icon.Swift,
  php: Icon.Php,
  rb: Icon.Ruby,
  go: Icon.Go,
  rs: Icon.Rust,
  sh: Icon.Bash,
  bash: Icon.Bash,
  zsh: Icon.Terminal,
  fish: Icon.Terminal,
  html: Icon.Html5,
  htm: Icon.Html5,
  css: Icon.Css3,
  scss: Icon.Css3,
  xml: Icon.Xml,
  svg: imageIcon,
  png: imageIcon,
  jpg: imageIcon,
  webp: imageIcon,
  dockerfile: Icon.Docker,
};
