export const DEBOUNCE_MS = 800;
export const DEFAULT_TARGET_LANG = "en";

export const DEFAULT_OLLAMA_HOST = "http://localhost:11434";
export const DEFAULT_MODEL = "gemma3:1b";

export interface ExtensionPreferences {
	ollamaHost?: string;
	defaultModel?: string;
	defaultTargetLang?: string;
}

export const LANGUAGES = [
	{ title: "Afar", value: "aa" },
	{ title: "Afrikaans", value: "af" },
	{ title: "Amharic", value: "am" },
	{ title: "Arabic", value: "ar" },
	{ title: "Assamese", value: "as" },
	{ title: "Azerbaijani", value: "az" },
	{ title: "Bengali", value: "bn" },
	{ title: "Bulgarian", value: "bg" },
	{ title: "Burmese", value: "my" },
	{ title: "Catalan", value: "ca" },
	{ title: "Chinese (Simplified)", value: "zh-Hans" },
	{ title: "Chinese (Traditional)", value: "zh-Hant" },
	{ title: "Croatian", value: "hr" },
	{ title: "Czech", value: "cs" },
	{ title: "Danish", value: "da" },
	{ title: "Dutch", value: "nl" },
	{ title: "English", value: "en" },
	{ title: "Estonian", value: "et" },
	{ title: "Filipino", value: "fil-PH" },
	{ title: "Finnish", value: "fi" },
	{ title: "French", value: "fr" },
	{ title: "Galician", value: "gl" },
	{ title: "Georgian", value: "ka" },
	{ title: "German", value: "de" },
	{ title: "Greek", value: "el" },
	{ title: "Gujarati", value: "gu" },
	{ title: "Hausa", value: "ha" },
	{ title: "Hebrew", value: "he" },
	{ title: "Hindi", value: "hi" },
	{ title: "Hungarian", value: "hu" },
	{ title: "Icelandic", value: "is" },
	{ title: "Igbo", value: "ig" },
	{ title: "Indonesian", value: "id" },
	{ title: "Italian", value: "it" },
	{ title: "Japanese", value: "ja" },
	{ title: "Javanese", value: "jv" },
	{ title: "Kannada", value: "kn" },
	{ title: "Kazakh", value: "kk" },
	{ title: "Khmer", value: "km" },
	{ title: "Korean", value: "ko" },
	{ title: "Kurdish", value: "ku" },
	{ title: "Lao", value: "lo" },
	{ title: "Latvian", value: "lv" },
	{ title: "Lithuanian", value: "lt" },
	{ title: "Macedonian", value: "mk" },
	{ title: "Malagasy", value: "mg" },
	{ title: "Malay", value: "ms" },
	{ title: "Malayalam", value: "ml" },
	{ title: "Marathi", value: "mr" },
	{ title: "Mongolian", value: "mn" },
	{ title: "Nepali", value: "ne" },
	{ title: "Norwegian", value: "nb" },
	{ title: "Oriya", value: "or" },
	{ title: "Oromo", value: "om" },
	{ title: "Pashto", value: "ps" },
	{ title: "Persian", value: "fa" },
	{ title: "Polish", value: "pl" },
	{ title: "Portuguese", value: "pt" },
	{ title: "Punjabi", value: "pa" },
	{ title: "Romanian", value: "ro" },
	{ title: "Russian", value: "ru" },
	{ title: "Serbian", value: "sr" },
	{ title: "Sindhi", value: "sd" },
	{ title: "Sinhala", value: "si" },
	{ title: "Slovak", value: "sk" },
	{ title: "Slovenian", value: "sl" },
	{ title: "Somali", value: "so" },
	{ title: "Spanish", value: "es" },
	{ title: "Swahili", value: "sw" },
	{ title: "Swedish", value: "sv" },
	{ title: "Tamil", value: "ta" },
	{ title: "Telugu", value: "te" },
	{ title: "Thai", value: "th" },
	{ title: "Tigrinya", value: "ti" },
	{ title: "Turkish", value: "tr" },
	{ title: "Ukrainian", value: "uk" },
	{ title: "Urdu", value: "ur" },
	{ title: "Uyghur", value: "ug" },
	{ title: "Uzbek", value: "uz" },
	{ title: "Vietnamese", value: "vi" },
	{ title: "Welsh", value: "cy" },
	{ title: "Wolof", value: "wo" },
	{ title: "Xhosa", value: "xh" },
	{ title: "Yoruba", value: "yo" },
	{ title: "Zulu", value: "zu" },
] as const;

export const TARGET_LANGUAGES = LANGUAGES;
