export const DEFAULT_SEARCH_RESULT_LIMIT = 100;
export const MAX_SEARCH_RESULT_LIMIT = 1000;

export const SEARCH_RESULT_LIMIT =
  DEFAULT_SEARCH_RESULT_LIMIT <= MAX_SEARCH_RESULT_LIMIT ? DEFAULT_SEARCH_RESULT_LIMIT : MAX_SEARCH_RESULT_LIMIT;

export const DATASET_NAME = "dataset";
