export interface Language {
	title: string;
	value: string;
}

/**
 * 59 languages matching the preference dropdown in package.json.
 * `title` is the native display name, `value` is the English identifier.
 * Both files must stay in sync.
 */
export const LANGUAGES: Language[] = [
	{ title: "Afrikaans", value: "Afrikaans" },
	{ title: "አማርኛ", value: "Amharic" },
	{ title: "العربية", value: "Arabic" },
	{ title: "বাংলা", value: "Bengali" },
	{ title: "Български", value: "Bulgarian" },
	{ title: "မြန်မာဘာသာ", value: "Burmese" },
	{ title: "Català", value: "Catalan" },
	{ title: "简体中文", value: "Chinese" },
	{ title: "Hrvatski", value: "Croatian" },
	{ title: "Čeština", value: "Czech" },
	{ title: "Dansk", value: "Danish" },
	{ title: "Nederlands", value: "Dutch" },
	{ title: "English", value: "English" },
	{ title: "Eesti", value: "Estonian" },
	{ title: "Filipino", value: "Filipino" },
	{ title: "Suomi", value: "Finnish" },
	{ title: "Français", value: "French" },
	{ title: "ქართული", value: "Georgian" },
	{ title: "Deutsch", value: "German" },
	{ title: "Ελληνικά", value: "Greek" },
	{ title: "ગુજરાતી", value: "Gujarati" },
	{ title: "Hausa", value: "Hausa" },
	{ title: "עברית", value: "Hebrew" },
	{ title: "हिन्दी", value: "Hindi" },
	{ title: "Magyar", value: "Hungarian" },
	{ title: "Indonesian", value: "Indonesian" },
	{ title: "Italiano", value: "Italian" },
	{ title: "日本語", value: "Japanese" },
	{ title: "ಕನ್ನಡ", value: "Kannada" },
	{ title: "ខ្មែរ", value: "Khmer" },
	{ title: "한국어", value: "Korean" },
	{ title: "Lietuvių", value: "Lithuanian" },
	{ title: "Bahasa Melayu", value: "Malay" },
	{ title: "മലയാളം", value: "Malayalam" },
	{ title: "मराठी", value: "Marathi" },
	{ title: "Монгол", value: "Mongolian" },
	{ title: "नेपाली", value: "Nepali" },
	{ title: "Norsk", value: "Norwegian" },
	{ title: "پښتو", value: "Pashto" },
	{ title: "فارسی", value: "Persian" },
	{ title: "Polski", value: "Polish" },
	{ title: "Português", value: "Portuguese" },
	{ title: "ਪੰਜਾਬੀ", value: "Punjabi" },
	{ title: "Română", value: "Romanian" },
	{ title: "Русский", value: "Russian" },
	{ title: "Српски", value: "Serbian" },
	{ title: "Español", value: "Spanish" },
	{ title: "Kiswahili", value: "Swahili" },
	{ title: "Svenska", value: "Swedish" },
	{ title: "தமிழ்", value: "Tamil" },
	{ title: "తెలుగు", value: "Telugu" },
	{ title: "ภาษาไทย", value: "Thai" },
	{ title: "正體中文", value: "Traditional Chinese" },
	{ title: "Türkçe", value: "Turkish" },
	{ title: "Українська", value: "Ukrainian" },
	{ title: "اردو", value: "Urdu" },
	{ title: "Tiếng Việt", value: "Vietnamese" },
	{ title: "Yorùbá", value: "Yoruba" },
	{ title: "isiZulu", value: "Zulu" },
];
